routes/admin.php
        Route::name('admin.products_categories.update')->put('/editar/{id}', 'Products\ProductCategoryController@update');
        Route::name('admin.products_categories.destroy')->delete('/excluir/{id}', 'Products\ProductCategoryController@destroy');

      });

      // Projects
      Route::prefix('projetos')->group(function() {
        Route::name('admin.projects.index')->get('/', 'Projects\ProjectController@index');
        Route::name('admin.projects.create')->get('/adicionar', 'Projects\ProjectController@create');
        Route::name('admin.projects.store')->post('/adicionar', 'Projects\ProjectController@store');
        Route::name('admin.projects.edit')->get('/editar/{id}', 'Projects\ProjectController@edit');
        Route::name('admin.projects.update')->put('/editar/{id}', 'Projects\ProjectController@update');
        Route::name('admin.projects.destroy')->delete('/excluir/{id}', 'Projects\ProjectController@destroy');

        // Projects Galleries
        Route::prefix('/{product_id}/galeria')->group(function(){
          Route::name('admin.projects_galleries.index')->get('/', 'Projects\ProjectGalleryController@index');
          Route::name('admin.projects_galleries.create')->get('/adicionar', 'Projects\ProjectGalleryController@create');
          Route::name('admin.projects_galleries.store')->post('/adicionar', 'Projects\ProjectGalleryController@store');
          Route::name('admin.projects_galleries.edit')->get('/editar/{id}', 'Projects\ProjectGalleryController@edit');
          Route::name('admin.projects_galleries.update')->put('/editar/{id}', 'Projects\ProjectGalleryController@update');
          Route::name('admin.projects_galleries.destroy')->delete('/excluir/{id}', 'Projects\ProjectGalleryController@destroy');
          Route::name('admin.projects_galleries.reorder')->post('/reordenar', 'Projects\ProjectGalleryController@reorder');
        });
      });

      // Projects Categories
      Route::prefix('projetos/categorias')->group(function() {
        Route::name('admin.projects_categories.index')->get('/', 'Projects\ProjectCategoryController@index');
        Route::name('admin.projects_categories.create')->get('/adicionar', 'Projects\ProjectCategoryController@create');
        Route::name('admin.projects_categories.store')->post('/adicionar', 'Projects\ProjectCategoryController@store');
        Route::name('admin.projects_categories.edit')->get('/editar/{id}', 'Projects\ProjectCategoryController@edit');
        Route::name('admin.projects_categories.update')->put('/editar/{id}', 'Projects\ProjectCategoryController@update');
        Route::name('admin.projects_categories.destroy')->delete('/excluir/{id}', 'Projects\ProjectCategoryController@destroy');
      });

      // Partners
      Route::prefix('parceiros')->group(function() {
        Route::name('admin.partners.index')->get('/', 'Partners\PartnerController@index');
        Route::name('admin.partners.create')->get('/adicionar', 'Partners\PartnerController@create');
        Route::name('admin.partners.store')->post('/adicionar', 'Partners\PartnerController@store');
        Route::name('admin.partners.edit')->get('/editar/{id}', 'Partners\PartnerController@edit');
        Route::name('admin.partners.update')->put('/editar/{id}', 'Partners\PartnerController@update');
        Route::name('admin.partners.destroy')->delete('/excluir/{id}', 'Partners\PartnerController@destroy');
      });

      // Partners Categories
      Route::prefix('parceiros/categorias')->group(function() {
        Route::name('admin.partners_categories.index')->get('/', 'Partners\PartnerCategoryController@index');
        Route::name('admin.partners_categories.create')->get('/adicionar', 'Partners\PartnerCategoryController@create');
        Route::name('admin.partners_categories.store')->post('/adicionar', 'Partners\PartnerCategoryController@store');
        Route::name('admin.partners_categories.edit')->get('/editar/{id}', 'Partners\PartnerCategoryController@edit');
        Route::name('admin.partners_categories.update')->put('/editar/{id}', 'Partners\PartnerCategoryController@update');
        Route::name('admin.partners_categories.destroy')->delete('/excluir/{id}', 'Partners\PartnerCategoryController@destroy');
      });

      // Posts
      Route::prefix('blog')->group(function() {
        Route::name('admin.posts.index')->get('/', 'Posts\PostController@index');
        Route::name('admin.posts.create')->get('/adicionar', 'Posts\PostController@create');
        Route::name('admin.posts.store')->post('/adicionar', 'Posts\PostController@store');
        Route::name('admin.posts.edit')->get('/editar/{id}', 'Posts\PostController@edit');
        Route::name('admin.posts.update')->put('/editar/{id}', 'Posts\PostController@update');
        Route::name('admin.posts.destroy')->delete('/excluir/{id}', 'Posts\PostController@destroy');
      });

      // Partners Categories
      Route::prefix('blog/categorias')->group(function() {
        Route::name('admin.posts_categories.index')->get('/', 'Posts\PostCategoryController@index');
        Route::name('admin.posts_categories.create')->get('/adicionar', 'Posts\PostCategoryController@create');
        Route::name('admin.posts_categories.store')->post('/adicionar', 'Posts\PostCategoryController@store');
        Route::name('admin.posts_categories.edit')->get('/editar/{id}', 'Posts\PostCategoryController@edit');
        Route::name('admin.posts_categories.update')->put('/editar/{id}', 'Posts\PostCategoryController@update');
        Route::name('admin.posts_categories.destroy')->delete('/excluir/{id}', 'Posts\PostCategoryController@destroy');
      });

      // Permissions
      Route::prefix('permissoes')->group(function() {
        Route::name('admin.permissions.index')->get('/', 'Users\PermissionController@index');
        Route::name('admin.permissions.create')->get('/adicionar', 'Users\PermissionController@create');
        Route::name('admin.permissions.store')->post('/adicionar', 'Users\PermissionController@store');
        Route::name('admin.permissions.edit')->get('/editar/{id}', 'Users\PermissionController@edit');
        Route::name('admin.permissions.update')->put('/editar/{id}', 'Users\PermissionController@update');
        Route::name('admin.permissions.destroy')->delete('/excluir/{id}', 'Users\PermissionController@destroy');
      });

      // Roles
      Route::prefix('grupos')->group(function() {
        Route::name('admin.roles.index')->get('/', 'Users\RoleController@index');
        Route::name('admin.roles.create')->get('/adicionar', 'Users\RoleController@create');
        Route::name('admin.roles.store')->post('/adicionar', 'Users\RoleController@store');
        Route::name('admin.roles.edit')->get('/editar/{id}', 'Users\RoleController@edit');
        Route::name('admin.roles.update')->put('/editar/{id}', 'Users\RoleController@update');
      });

      // Users
      Route::prefix('usuarios')->group(function() {
        Route::name('admin.users.index')->get('/', 'Users\UserController@index');
        Route::name('admin.users.create')->get('/adicionar', 'Users\UserController@create');
        Route::name('admin.users.store')->post('/adicionar', 'Users\UserController@store');
        Route::name('admin.users.edit')->get('/editar/{id}', 'Users\UserController@edit');
        Route::name('admin.users.update')->put('/editar/{id}', 'Users\UserController@update');
        Route::name('admin.users.activate')->get('/ativar/{id}', 'Users\UserController@activate');
        Route::name('admin.users.deactivate')->get('/desativar/{id}', 'Users\UserController@deactivate');
      });

      // Settings
      Route::prefix('configuracoes')->group(function() {
        Route::name('admin.settings.index')->get('/', 'Settings\SettingController@index');
        Route::name('admin.settings.create')->get('/adicionar', 'Settings\SettingController@create');
        Route::name('admin.settings.store')->post('/adicionar', 'Settings\SettingController@store');
        Route::name('admin.settings.edit')->get('/editar/{id}', 'Settings\SettingController@edit');
        Route::name('admin.settings.update')->put('/editar/{id}', 'Settings\SettingController@update');
        Route::name('admin.settings.destroy')->delete('/excluir/{id}', 'Settings\SettingController@destroy');
      });

      // Audit
      Route::prefix('auditoria')->group(function() {
        Route::name('admin.audits.index')->get('/', 'Audits\AuditController@index');
        Route::name('admin.audits.show')->get('/{id}', 'Audits\AuditController@show');
      });

      // Analytics
      Route::name('admin.analytics.index')->get('/acessos', 'Analytics\AnalyticController@index');

      // Messages
      Route::prefix('mensagens')->group(function() {
        Route::name('admin.messages.index')->get('/', 'Messages\MessageController@index');
        Route::name('admin.messages.show')->get('/{id}', 'Messages\MessageController@show');
        Route::name('admin.messages.destroy')->delete('/excluir/{id}', 'Messages\MessageController@destroy');
      });

      // Reports
      Route::prefix('/relatorios')->group(function() {
        Route::name('admin.reports.index')->get('/', 'Reports\ReportController@index');
      });

      // Releases
      Route::prefix('destaques')->group(function() {
        Route::name('admin.releases.index')->get('/', 'Releases\ReleaseController@index');
        Route::name('admin.releases.create')->get('/adicionar', 'Releases\ReleaseController@create');
        Route::name('admin.releases.store')->post('/adicionar', 'Releases\ReleaseController@store');
        Route::name('admin.releases.edit')->get('/editar/{id}', 'Releases\ReleaseController@edit');
        Route::name('admin.releases.update')->put('/editar/{id}', 'Releases\ReleaseController@update');
        Route::name('admin.releases.destroy')->delete('/excluir/{id}', 'Releases\ReleaseController@destroy');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::name('home.index')->get('/', 'Front\HomeController@index');

// About
Route::name('about.index')->get('/sobre', 'Front\AboutController@index');

// Contact
Route::name('contact.index')->get('/contato', 'Front\ContactController@index');

// News
// Route::name('posts.index')->get('/blog', 'Front\PostController@index');
// Route::name('posts.show')->get('/blog/{category}/{slug}', 'Front\PostController@show');

// Projects
Route::name('projects.index')->get('/projetos/', 'Front\ProjectController@index');
Route::name('projects.show')->get('/projetos/{category}/{slug}', 'Front\ProjectController@show');

// Products
Route::name('products.index')->get('/parceiros', 'Front\ProductController@index');

// Sitemap
Route::name('sitemap')->get('/sitemap', 'Front\SitemapController@index');

/**
 * Api Routes
 */
Route::prefix('api')->group(function()
{
  // Messages
  Route::name('api.message.store')->post('/enviar-mensagem', 'Api\Messages\MessageController@store');

});

app/Models/Core/Audit.php
<?php

namespace App\Models\Core;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Audit as AuditContract;
use OwenIt\Auditing\Audit as AuditTrait;
use Carbon\Carbon;

class Audit extends Model implements AuditContract
{
  use AuditTrait;

  protected $guarded = [];

  protected $casts = [
    'old_values' => 'json',
    'new_values' => 'json'
  ];

  /**
   * Scopes
  */
  public function scopeToday($query)
  {
    $query->whereDate('created_at', Carbon::today());
  }

  /**
   * Accesors
   */
  public function getTypeNameAttribute()
  {
    $auditableType = class_basename($this->auditable_type);

    // Get types
    $types = config('panel.audit.types');

    // Return type name
    return isset($types[$auditableType]) ? $types[$auditableType] : 'Indefinido';
  }

  public function getActionNameAttribute()
  {
    // Get actions
    $actions = config('panel.audit.actions');

    // Return action name
    return $actions[$this->event];
  }
}

app/Http/Controllers/Admin/Audits/AuditController.php
<?php

namespace App\Http\Controllers\Admin\Audits;

use App\Http\Controllers\Admin\BaseController;
use Illuminate\Http\Request;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
use Crumbs;
use Auth;
use App\Models\Core\Audit;
use App\Models\Auth\User;
use Carbon\Carbon;

class AuditController extends BaseController
{
  use SEOToolsTrait;

  private $audits;
  private $users;

  public function __construct(Audit $audits, User $users)
  {
    // Middlewares
    $this->middleware('permission:view_audits', ['only' => ['index', 'show']]);

    // Dependency Injection
    $this->audits = $audits;
    $this->users = $users;
  }

  /**
   * Display a listing of the resource.
   * @return Response
   */
  public function index(Request $request)
  {
    // Fetch all users
    $users = $this->users->isRoot(Auth::user())->orderBy('first_name', 'ASC')->get() ->pluck('full_name', 'id');

    // Start query
    $query = $this->audits->latest();

    // Filter by data param
    if ($request->filled('data')):
      $date = Carbon::createFromFormat('d-m-Y', $request->get('data'))->format('Y-m-d');
      $query->whereDate('created_at', $date);
    endif;

    // Filter by usuario param
    if ($request->filled('usuario')):
      $query->where('user_id', $request->get('usuario'));
    endif;

    // Filter by tipo param
    if ($request->filled('tipo')):
      $query->where('user_id', $request->get('tipo'));
    endif;

    // Filter by acao param
    if ($request->filled('acao')):
      $query->where('event', $request->get('acao'));
    endif;

    // Fetch all results
    $results = $query->paginate(5)->appends($request->except('page'));

    // Set meta tags
    $this->seo()->setTitle('Auditoria');

    // Return view
    return view('admin.audits.index', compact('results', 'users'));
  }

  /**
   * Show the specified resource.
   * @return Response
   */
  public function show($id)
  {
    // Fetch result by id
    $result = $this->audits->findOrFail($id);

    // Set meta tags
    $this->seo()->setTitle('Auditoria - Log');

    // Return view
    return view('admin.audits.show', compact('result'));
  }
}

resources/views/admin/audits/index.blade.php
@extends('admin.layouts.default')

@section('content')
  <div class="content-wrapper">
    @include('flash::message')
    <div class="row">
      {{ Breadcrumbs::render('audits.index') }}
    </div>
    <div class="row">
      <div class="col-md-12 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                {!! Form::open(['route' => 'admin.audits.index', 'method' => 'GET', 'novalidate', 'role' => 'form']) !!}
                  <div class="row">
                    <div class="form-group no-margin col-md-2 col-lg-2 col-sm-12">
                      {!! Form::text('data', Request::get('data'), ['class' => 'form-control form-control-lg js-datepicker', 'placeholder' => 'Data']) !!}
                    </div>
                    <div class="form-group no-margin col-md-2 col-lg-2 col-sm-12">
                      {!! Form::select('usuario', $users, Request::get('usuario'), ['class' => 'form-control form-control-lg', 'placeholder' => 'Usuário']) !!}
                    </div>
                    <div class="form-group no-margin col-md-2 col-lg-2 col-sm-12">
                      {!! Form::select('tipo', config('panel.audit.types'), Request::get('tipo'), ['class' => 'form-control form-control-lg', 'placeholder' => 'Tipo']) !!}
                    </div>
                    <div class="form-group no-margin col-md-2 col-lg-2 col-sm-12">
                      {!! Form::select('acao', config('panel.audit.actions'), Request::get('acao'), ['class' => 'form-control form-control-lg', 'placeholder' => 'Ação']) !!}
                    </div>
                    <div class="form-group no-margin col-md-2 col-lg-2 col-sm-12">
                      <button type="button" class="btn btn-danger btn-lg btn-block"><i class="fa fa-times"></i></button>
                    </div>
                    <div class="form-group no-margin col-md-2 col-lg-2 col-sm-12">
                      <button type="submit" class="btn btn-success btn-lg btn-block"><i class="fa fa-search"></i></button>
                    </div>
                  </div>
                {!! Form::close() !!}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Auditoria</h4>
            <span class="legend">Total: {{ $results->total() }}</span>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th> Usuário </th>
                  <th> Tipo </th>
                  <th> Ação </th>
                  <th> Horário </th>
                  <th> Ações </th>
                </tr>
              </thead>
              <tbody>
                @foreach($results as $result)
                  <tr>
                    <td> {{ $result->user->full_name }} </td>
                    <td> {{ $result->type_name }} </td>
                    <td> {{ $result->action_name }} </td>
                    <td> {{ $result->created_at->format('d/m/Y H:i') }} </td>
                    <td>
                      <a href="{{ route('admin.audits.show', ['id' => $result->id]) }}" class="action-icon -success" data-toggle="tooltip" data-placement="bottom" title="Visualizar" data-original-title="Visualizar"><i class="icon-eye"></i></a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
          @include('admin.partials.pagination')
        </div>
      </div>
    </div>
  </div>
@endsection