routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')->group(function(){

  /**
   * Public Routes
   */
  Route::middleware('guest.admin')->group(function(){
    // Login
    Route::name('admin.session.login')->get('/acessar', 'Admin\Session\SessionController@showLoginForm');
    Route::name('admin.session.login')->post('/acessar', 'Admin\Session\SessionController@login');
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    // Social Login
    Route::name('admin.social.redirect')->get('/social/redirect/{provider}', 'Admin\Session\SocialController@redirectToProvider');
    Route::name('admin.social.handle')->get('/social/handle/{provider}', 'Admin\Session\SocialController@handleProviderCallback');

    // Reset Password
    Route::name('admin.password.forgot')->get('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@showLinkRequestForm');
    Route::name('admin.password.processForgot')->post('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@sendResetLinkEmail');
    Route::name('admin.password.reset')->get('/cadastrar-senha/{token}', 'Admin\Session\ResetPasswordController@showResetForm');
    Route::name('admin.password.processReset')->post('/cadastrar-senha', 'Admin\Session\ResetPasswordController@reset');
  });

  /**
   * Protected Routes
   */
  Route::middleware(['auth.admin'])->group(function(){

    // Api Routes
    Route::prefix('api')->group(function(){
      // Media
      Route::prefix('media/images')->group(function(){
        Route::name('admin.media.index')->get('/', 'Api\MediaLibrary\MediaLibraryController@index');
        Route::name('admin.media.store')->post('/adicionar', 'Api\MediaLibrary\MediaLibraryController@store');
      });

      // Places
      Route::name('admin.states.list')->get('/estados', 'Admin\Places\StateController@getStates');
      Route::name('admin.cities.list')->get('/cidades', 'Admin\Places\CityController@getCities');
      Route::name('admin.neighborhoods.list')->get('/bairros', 'Admin\Places\NeighborhoodController@getNeighborhoods');
    });

    // First access
    Route::name('admin.activation.create')->get('/primeiro-acesso', 'Admin\Session\ActivationController@showActivationForm');
    Route::name('admin.activation.processCreate')->post('/primeiro-acesso', 'Admin\Session\ActivationController@store');

    // Logout
    Route::name('admin.session.logout')->get('/sair', 'Admin\Session\SessionController@logout');

    // Check first access
    Route::middleware(['first.access'])->namespace('Admin')->group(function() {

      // Dashboard
      Route::name('admin.dashboard.index')->get('/', 'Dashboard\DashboardController@index');

      // Account
      Route::prefix('perfil')->group(function() {
        Route::name('admin.accounts.show')->get('/', 'Users\AccountController@show');
        Route::name('admin.accounts.edit')->get('/atualizar', 'Users\AccountController@edit');
        Route::name('admin.accounts.update')->put('/atualizar', 'Users\AccountController@update');
      });

       // Products
      Route::prefix('produtos')->group(function() {
        Route::name('admin.products.index')->get('/', 'Products\ProductController@index');
        Route::name('admin.products.create')->get('/adicionar', 'Products\ProductController@create');
        Route::name('admin.products.store')->post('/adicionar', 'Products\ProductController@store');
        Route::name('admin.products.edit')->get('/editar/{id}', 'Products\ProductController@edit');
        Route::name('admin.products.update')->put('/editar/{id}', 'Products\ProductController@update');
        Route::name('admin.products.destroy')->delete('/excluir/{id}', 'Products\ProductController@destroy');

        // Projects Galleries
        Route::prefix('/{product_id}/galeria')->group(function(){
          Route::name('admin.products_galleries.index')->get('/', 'Products\ProductGalleryController@index');
          Route::name('admin.products_galleries.create')->get('/adicionar', 'Products\ProductGalleryController@create');
          Route::name('admin.products_galleries.store')->post('/adicionar', 'Products\ProductGalleryController@store');
          Route::name('admin.products_galleries.edit')->get('/editar/{id}', 'Products\ProductGalleryController@edit');
          Route::name('admin.products_galleries.update')->put('/editar/{id}', 'Products\ProductGalleryController@update');
          Route::name('admin.products_galleries.destroy')->delete('/excluir/{id}', 'Products\ProductGalleryController@destroy');
          Route::name('admin.products_galleries.reorder')->post('/reordenar', 'Products\ProductGalleryController@reorder');
        });
      });

      // Products Categories
      Route::prefix('produtos/categorias')->group(function() {
        Route::name('admin.products_categories.index')->get('/', 'Products\ProductCategoryController@index');
        Route::name('admin.products_categories.create')->get('/adicionar', 'Products\ProductCategoryController@create');
        Route::name('admin.products_categories.store')->post('/adicionar', 'Products\ProductCategoryController@store');
        Route::name('admin.products_categories.edit')->get('/editar/{id}', 'Products\ProductCategoryController@edit');
        Route::name('admin.products_categories.update')->put('/editar/{id}', 'Products\ProductCategoryController@update');
        Route::name('admin.products_categories.destroy')->delete('/excluir/{id}', 'Products\ProductCategoryController@destroy');

      });

      // Projects
      Route::prefix('projetos')->group(function() {
        Route::name('admin.projects.index')->get('/', 'Projects\ProjectController@index');
        Route::name('admin.projects.create')->get('/adicionar', 'Projects\ProjectController@create');
        Route::name('admin.projects.store')->post('/adicionar', 'Projects\ProjectController@store');
        Route::name('admin.projects.edit')->get('/editar/{id}', 'Projects\ProjectController@edit');
        Route::name('admin.projects.update')->put('/editar/{id}', 'Projects\ProjectController@update');
        Route::name('admin.projects.destroy')->delete('/excluir/{id}', 'Projects\ProjectController@destroy');

        // Projects Galleries
        Route::prefix('/{product_id}/galeria')->group(function(){
          Route::name('admin.projects_galleries.index')->get('/', 'Projects\ProjectGalleryController@index');
          Route::name('admin.projects_galleries.create')->get('/adicionar', 'Projects\ProjectGalleryController@create');
          Route::name('admin.projects_galleries.store')->post('/adicionar', 'Projects\ProjectGalleryController@store');
          Route::name('admin.projects_galleries.edit')->get('/editar/{id}', 'Projects\ProjectGalleryController@edit');
          Route::name('admin.projects_galleries.update')->put('/editar/{id}', 'Projects\ProjectGalleryController@update');
          Route::name('admin.projects_galleries.destroy')->delete('/excluir/{id}', 'Projects\ProjectGalleryController@destroy');
          Route::name('admin.projects_galleries.reorder')->post('/reordenar', 'Projects\ProjectGalleryController@reorder');
        });
      });

      // Projects Categories
      Route::prefix('projetos/categorias')->group(function() {
        Route::name('admin.projects_categories.index')->get('/', 'Projects\ProjectCategoryController@index');
        Route::name('admin.projects_categories.create')->get('/adicionar', 'Projects\ProjectCategoryController@create');
        Route::name('admin.projects_categories.store')->post('/adicionar', 'Projects\ProjectCategoryController@store');
        Route::name('admin.projects_categories.edit')->get('/editar/{id}', 'Projects\ProjectCategoryController@edit');
        Route::name('admin.projects_categories.update')->put('/editar/{id}', 'Projects\ProjectCategoryController@update');
        Route::name('admin.projects_categories.destroy')->delete('/excluir/{id}', 'Projects\ProjectCategoryController@destroy');
      });

      // Partners
      Route::prefix('parceiros')->group(function() {
        Route::name('admin.partners.index')->get('/', 'Partners\PartnerController@index');
        Route::name('admin.partners.create')->get('/adicionar', 'Partners\PartnerController@create');
        Route::name('admin.partners.store')->post('/adicionar', 'Partners\PartnerController@store');
        Route::name('admin.partners.edit')->get('/editar/{id}', 'Partners\PartnerController@edit');
        Route::name('admin.partners.update')->put('/editar/{id}', 'Partners\PartnerController@update');
        Route::name('admin.partners.destroy')->delete('/excluir/{id}', 'Partners\PartnerController@destroy');
      });

      // Partners Categories
      Route::prefix('parceiros/categorias')->group(function() {
        Route::name('admin.partners_categories.index')->get('/', 'Partners\PartnerCategoryController@index');
        Route::name('admin.partners_categories.create')->get('/adicionar', 'Partners\PartnerCategoryController@create');
        Route::name('admin.partners_categories.store')->post('/adicionar', 'Partners\PartnerCategoryController@store');
        Route::name('admin.partners_categories.edit')->get('/editar/{id}', 'Partners\PartnerCategoryController@edit');
        Route::name('admin.partners_categories.update')->put('/editar/{id}', 'Partners\PartnerCategoryController@update');
        Route::name('admin.partners_categories.destroy')->delete('/excluir/{id}', 'Partners\PartnerCategoryController@destroy');
      });

      // Posts
      Route::prefix('blog')->group(function() {
        Route::name('admin.posts.index')->get('/', 'Posts\PostController@index');
        Route::name('admin.posts.create')->get('/adicionar', 'Posts\PostController@create');
        Route::name('admin.posts.store')->post('/adicionar', 'Posts\PostController@store');
        Route::name('admin.posts.edit')->get('/editar/{id}', 'Posts\PostController@edit');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::name('home.index')->get('/', 'Front\HomeController@index');

// About
Route::name('about.index')->get('/sobre', 'Front\AboutController@index');

// Contact
Route::name('contact.index')->get('/contato', 'Front\ContactController@index');

// News
// Route::name('posts.index')->get('/blog', 'Front\PostController@index');
// Route::name('posts.show')->get('/blog/{category}/{slug}', 'Front\PostController@show');

// Projects
Route::name('projects.index')->get('/projetos/', 'Front\ProjectController@index');
Route::name('projects.show')->get('/projetos/{category}/{slug}', 'Front\ProjectController@show');

// Products
Route::name('products.index')->get('/parceiros', 'Front\ProductController@index');

// Sitemap
Route::name('sitemap')->get('/sitemap', 'Front\SitemapController@index');

/**
 * Api Routes
 */
Route::prefix('api')->group(function()
{
  // Messages
  Route::name('api.message.store')->post('/enviar-mensagem', 'Api\Messages\MessageController@store');

});

app/Models/Partner/Partner.php
<?php

namespace App\Models\Partner;

use Illuminate\Database\Eloquent\Model;
use App\Models\Auth\User;
use OwenIt\Auditing\Contracts\Auditable as AuditableInterface;
use OwenIt\Auditing\Auditable as AuditableTrait;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Cviebrock\EloquentSluggable\Sluggable;

class Partner extends Model implements HasMedia, AuditableInterface
{
  use AuditableTrait;
  use HasMediaTrait;

  protected $fillable = [
    'name',
    'refer',
    'target',
    'position',
    'active',
    'category_id',
    'user_id'
  ];

  protected $casts = [
    'publish' => 'boolean'
  ];

  /**
   * Auditable Config
   */
  protected $auditInclude = [
    'name',
    'refer',
    'target',
    'position',
    'active',
    'category_id',
    'user_id'
  ];

  /**
  * Scopes
  */
  public function scopeActived($query)
  {
    $query->where('active', true);
  }

  public function scopeWhereCategoryId($query, $id)
  {
    $query->whereHas('category', function ($q) use ($id) {
      $q->where('id', $id);
    });
  }

  public function scopePosition($query)
  {
    $query->orderBy('position', 'ASC');
  }

  /**
  * Relations
  */
  public function creator()
  {
    return $this->belongsTo(User::class, 'user_id')->select('id', 'first_name', 'last_name');
  }

  public function category()
  {
    return $this->belongsTo(PartnerCategory::class, 'category_id');
  }

  /**
  * Accesors
  */
  public function getPhotoAttribute()
  {
    $image = $this->getMedia('partner')->first();

    return isset($image) ? $image->getUrl() : null;
  }

}

resources/views/admin/partials/breadcrumbs.blade.php
@if (count($breadcrumbs))
  <div class="col-md-12 col-lg-12 col-sm-12">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-primary">
        @foreach ($breadcrumbs as $breadcrumb)
          @if ($breadcrumb->url && !$loop->last)
            <li class="breadcrumb-item">
              <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
            </li>
          @else
            <li class="breadcrumb-item active">
              <a href="#" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
            </li>
          @endif
        @endforeach
      </ol>
    </nav>
  </div>
@endif

resources/views/admin/partials/favicons.blade.php
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('/assets/favicons/apple-touch-icon.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('/assets/favicons/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('/assets/favicons/favicon-16x16.png') }}">
<link rel="manifest" href="{{ asset('/assets/favicons/site.webmanifest') }}">
<link rel="mask-icon" href="{{ asset('/assets/favicons/safari-pinned-tab.svg') }}" color="#5bbad5">
<link rel="shortcut icon" href="{{ asset('/assets/favicons/favicon.ico') }}">
<meta name="msapplication-TileColor" content="#00a300">
<meta name="msapplication-config" content="{{ asset('/assets/favicons/browserconfig.xml') }}">
<meta name="theme-color" content="#ffffff">

resources/views/admin/partials/footer.blade.php
<footer class="footer">
  <div class="container clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018
      <a href="{{ route('home.index') }}" target="_blank" title="Fecimal - Todos os direitos reservados.">Fecimal</a>. Todos os direitos reservados.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Criado e mantido por J&L
    </span>
  </div>
</footer>

resources/views/admin/partials/navbar.blade.php
 <nav class="navbar horizontal-layout col-lg-12 col-12 p-0">
    <div class="container d-flex flex-row nav-top">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top">
        <a class="navbar-brand brand-logo" href="{{ route('admin.dashboard.index') }}" title="Home">
          <img src="{{ asset('/assets/images/brand.svg') }}" alt="logo" /> </a>
        <a class="navbar-brand brand-logo-mini" href="{{ route('admin.dashboard.index') }}" title="Home">
          <img src="{{ asset('/assets /images/brand.svg') }}" alt="logo" /> </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown d-none d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">Olá,
              {{ auth()->user()->first_name }}
              <img class="img-xs rounded-circle ml-3" src="{{ auth()->user()->photo }}" alt="Profile image"> </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a href="{{ route('admin.accounts.show') }}" class="dropdown-item mt-2" title="Perfil"> Perfil </a>
              <a href="{{ route('home.index') }}" target="_blank" class="dropdown-item mt-2" title="Ir ao site"> Ir ao site </a>
              <a href="{{ route('admin.session.logout') }}" class="dropdown-item" title="Sair"> Sair </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </div>
    <div class="nav-bottom">
      <div class="container">
        <ul class="nav page-navigation">
          <li class="nav-item {{ active('admin.dashboard.index', 'active') }}">
            <a href="{{ route('admin.dashboard.index') }}" class="nav-link" title="Dashboard">
              <i class="link-icon mdi mdi-airplay"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
     {{--      <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="link-icon mdi mdi-chart-line"></i>
              <span class="menu-title">Acessos</span>
            </a>
          </li> --}}
          <li class="nav-item {{ active('admin.messages.index', 'active') }}">
            <a href="{{ route('admin.messages.index') }}" class="nav-link" title="Mensagens">
              <i class="link-icon mdi mdi-comment-outline"></i>
              <span class="menu-title">Mensagens</span>
            </a>
          </li>
          <li class="nav-item {{ active('admin.audits.index', 'active') }}">
            <a href="{{ route('admin.audits.index') }}" class="nav-link" title="Auditoria">
              <i class="link-icon mdi mdi-equal-box"></i>
              <span class="menu-title">Auditoria</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="link-icon mdi mdi-cube-outline"></i>
              <span class="menu-title ">Site</span>
              <i class="menu-arrow "></i>
            </a>
            <div class="submenu">
              <ul class="submenu-item ">
                @foreach(config('panel.menu') as $menu)
                  @can($menu['permission'])
                  <li class="nav-item {{ active($menu['route'], 'active') }}">
                    <a class="nav-link" href="{{ route($menu['route']) }}" title="{{ $menu['name'] }}">{{ $menu['name'] }}</a>
                  </li>
                  @endcan
                @endforeach
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

resources/views/admin/partials/pagination.blade.php
<div class="card-footer">
  <div class="col-lg-12">
    <nav class="pull-right">
      <ul class="pagination rounded">
        {!! $results->render() !!}
      </ul>
    </nav>
  </div>
</div>

resources/views/admin/partials/scripts.blade.php
<script src="{{ asset('/admin_assets/vendors/js/vendor.bundle.base.js') }}"></script>
<script src="{{ asset('/admin_assets/vendors/js/vendor.bundle.addons.js') }}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{{ asset('/admin_assets/js/shared/off-canvas.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/hoverable-collapse.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/misc.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/settings.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/todolist.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/tooltips.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/iCheck.js') }}"></script>
<script src="{{ asset('/admin_assets/js/shared/file-upload.js') }}"></script>
<script src="{{ asset('/admin_assets/js-duallistbox/jquery.bootstrap-duallistbox.min.js') }}"></script>

<!-- CDNS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>

<!-- endinject -->
<!-- Custom js for this page-->
<script src="{{ asset('/admin_assets/js/mask.js') }}"></script>
<script src="{{ asset('/admin_assets/js/demo_2/script.js') }}"></script>
<!-- End custom js for this page-->

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/pt.js"></script>
<script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>

<script src="{{ asset('/admin_assets/vendors/summernote/dist/summernote-bs4.min.js') }}"></script>
<script src="{{ asset('/admin_assets/js/custom.js') }}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.26.14/sweetalert2.all.min.js"></script>

@stack('scripts')

resources/views/admin/partials/seo.blade.php
<div class="card review-card bottom">
  <div class="card-header header-sm d-flex justify-content-between align-items-center blue">
    <h4 class="card-title"> <i class="icon-sm link-icon mdi mdi-code-tags"></i> Otimização para buscadores</h4>
    {!! Form::hidden('seo[id]', (isset($result->seo)) ? $result->seo->id : null) !!}
  </div>
  <div class="card-body">
    <div class="row">
      <div class="form-group col-md-12 col-lg-12 col-sm-12">
        {!! Form::label('seo[meta_title]', 'Título da página', []) !!}
        {!! Form::text('seo[meta_title]', (isset($result->seo)) ? $result->seo->meta_title : old('seo.meta_title'), ['class' => 'form-control form-control-lg']) !!}
        @if($errors->has('seo.meta_title'))
          <span class="help-block">{{ $errors->first('seo.meta_title') }}</span>
        @endif
      </div>
      <div class="form-group col-md-12 col-lg-12 col-sm-12">
        {!! Form::label('seo[meta_description]', 'Descrição da página', []) !!}
        {!! Form::text('seo[meta_description]', old('seo[meta_description]'), ['class' => 'form-control form-control-lg']) !!}
        @if($errors->has('seo.meta_description'))
          <span class="help-block">{{ $errors->first('seo.meta_description') }}</span>
        @endif
      </div>
      <div class="form-group col-sm-12 col-lg-12 col-md-12">
        {!! Form::label('seo[image_facebook]', 'Capa facebook (1200x630)', ['']) !!}
        {!! Form::file('seo[image_facebook]', ['class' => 'file-upload-default']) !!}
        <div class="input-group col-xs-12">
          <input type="text" class="form-control file-upload-info" disabled="" placeholder="">
          <span class="input-group-append">
            <button class="file-upload-browse btn btn-default" type="button">Selecionar</button>
          </span>
        </div>
        @if($errors->has('seo.image_facebook'))
          <span class="help-block">{{ $errors->first('seo.image_facebook') }}</span>
        @endif
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/styles.blade.php
<!-- plugins:css -->
<link rel="stylesheet" href="{{ asset('/admin_assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_assets/vendors/iconfonts/puse-icons-feather/feather.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_assets/vendors/css/vendor.bundle.base.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_assets/vendors/css/vendor.bundle.addons.css') }}">

<link rel="stylesheet" href="{{ asset('admin_assets/vendors/iconfonts/font-awesome/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/vendors/iconfonts/simple-line-icon/css/simple-line-icons.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/vendors/icheck/skins/all.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/js-duallistbox/bootstrap-duallistbox.min.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
<link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
<!-- endinject -->
<!-- plugin css for this page -->
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="{{ asset('/admin_assets/css/shared/style.css') }}">
<!-- endinject -->
<!-- Layout styles -->
<link rel="stylesheet" href="{{ asset('/admin_assets/css/demo_2/style.css') }}">

<!-- Custom -->
<link rel="stylesheet" href="{{ asset('/admin_assets/css/custom.css') }}">

<link rel="stylesheet" href="{{ asset('/admin_assets/css/css_dropify/dropzone.min.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_assets/vendors/summernote/dist/summernote-bs4.css') }}">